use std::error::Error;

pub fn execute() -> Result<(), Box<dyn Error>> {
    Ok(())
}
